name: personal_journal
description: A new Flutter project.

publish_to: 'none' # hapus jika ingin publish ke pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  image_picker: ^0.8.7
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
